trigger:
  branches:
    include:
      - users/rony/302-applepay-0730
  paths:
    include:
      - src/order/**

pool:
  vmImage: ubuntu-latest

  variables:
    - group: dev

steps:
  # Set up Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
      checkLatest: true

  # Install dependencies
  - script: |
      cd src/order
      npm install -g @ionic/cli  # Install Ionic CLI
      npm ci
    displayName: 'Install dependencies'

  # Build the Ionic app
  - script: |
      cd src/order
      ionic build --prod  # Build the app for production
    displayName: 'Build Ionic Project'

  # Copy Apple Pay domain verification file
  - script: |
      cd src/order      
      mkdir -p dist/.well-known
      cp -f apple-verification-files/apple-developer-merchantid-domain-association.gravity dist/.well-known/apple-developer-merchantid-domain-association
    displayName: 'Postbuild: Copy Apple Pay Verification File'

  - script: |
      cd src/order/dist
      echo "📂 Final dist/ contents:"
      find . -type f -exec stat --format='%y %s bytes %n' {} \; | sort
    displayName: 'Verify dist/ contents'

  # Deploy to Azure Static Web App
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(azure_static_web_apps_api_token_order)
      app_location: 'src/order'
      api_location: ''
      output_location: 'dist'
      app_build_command: 'npm run build'
      api_build_command: 'rm -rf ./node_modules/@next/swc-* && rm -rf ./.next/cache'
