trigger:
  branches:
    include:
      - users/prakash/275-274
  paths:
    include:
      - src/manage/**

pool:
  vmImage: ubuntu-latest

  variables:
    - group: dev

steps:
  # Step 1: Set up Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
      checkLatest: true

  # Step 2: Install dependencies
  - script: |
      cd src/manage
      npm install -g @ionic/cli  # Install Ionic CLI
      npm ci
    displayName: 'Install dependencies'

  # Step 3: Build the Ionic app
  - script: |
      cd src/manage
      ionic build --prod  # Build the app for production
    displayName: 'Build Ionic Project'

  # Step 4: Deploy to Azure Static Web App
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(azure_static_web_apps_api_token_manage)
      app_location: 'src/manage'
      api_location: ''
      output_location: 'dist'
      app_build_command: 'npm run build'
      api_build_command: 'rm -rf ./node_modules/@next/swc-* && rm -rf ./.next/cache'
